POST http://taskmanager.dev/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMGM0YTg1MTU5YTBkMDAyMzU2M2ExYSIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlhdCI6MTU5NDY0MjMxOCwiZXhwIjoxNTk0NjQzMjE4fQ.2LwQdYLRuZDEPk0jmSM8bX3RhGYGg2fZiQi_w7vASLM

{
  "projectId": "5f0c4ab3a6fa080018b35b13",
  "description": "Description 2"
}

###

GET http://taskmanager.dev/api/tasks/5f0c4ab3a6fa080018b35b13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMGM0YTg1MTU5YTBkMDAyMzU2M2ExYSIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlhdCI6MTU5NDY0MjMxOCwiZXhwIjoxNTk0NjQzMjE4fQ.2LwQdYLRuZDEPk0jmSM8bX3RhGYGg2fZiQi_w7vASLM